### ISSUE TITLE
Tag with 0.3.3

### ISSUE THREAD

**Issue by cbankester** [nitram509/macaroons.js#2]
Master is still tagged with 0.3.2 as the latest, so npm isn't picking up the changes in 0.3.3.

To get around it right now, I'm using
```json
...
"macaroons.js": "git@github.com:nitram509/macaroons.js#8a2360893008b8e0f0af45c18a1e58adb5ac8fed",
...
```
in the package.json to specify the master commit.

**Comment by nitram509** [comment]
Thanks for pointing this out.
I've updated some libs and released 0.3.4 to npmjs.org

Regards
Martin
