### ISSUE TITLE
Error verifying macaroon: Missing second parameter 'message'.

### ISSUE THREAD

**Issue by redimongo** [nitram509/macaroons.js#319]
I am not sure why we are getting this error when I use 

```
    const buyMacaroon = new MacaroonsBuilder(location, SECRET_KEY, "just testing to see if this works")
      .add_first_party_caveat(`purchase_hash=${purchaseHash}`)
      .getMacaroon();
```

but then I try and verify using
```
    var verifier = new MacaroonsVerifier(macaroon);
    var valid = verifier.isValid(SECRET_KEY);

```

and it spits out` Error verifying macaroon: Missing second parameter 'message'.`

would love to know what I am doing wrong please.

version I am using     "macaroons.js": "^0.3.9",

**Comment by nitram509** [comment]
Hi,

the code looks totally legit... there must be something else happen.

I've quickly crafted this pure `x.js` file (below), which can simply executed via `node x.js` and gives no error.
This example is based on your code above and adds also the serialization, which is important to do, when sending a macaroon to a client app.

Does this answer or help you?

```javascript
var MacaroonsVerifier = require("./index").MacaroonsVerifier;
var MacaroonsBuilder = require("./index").MacaroonsBuilder;
var MacaroonsDeSerializer = require("./index").MacaroonsDeSerializer;

var SECRET_KEY = 'this is our super secret key; only we should know it';
var location = '127.0.0.1'

// ------------------

const buyMacaroon = new MacaroonsBuilder(location, SECRET_KEY, "just testing to see if this works")
    .add_first_party_caveat(`purchase_hash=XXXYYYZZZ`)
    .getMacaroon();

let packet = buyMacaroon.serialize()

// ------------------

macaroon = MacaroonsDeSerializer.deserialize(packet);

var verifier = new MacaroonsVerifier(macaroon);
var valid = verifier.isValid(SECRET_KEY);
```

**Comment by redimongo** [comment]
Yeah I found the error and fixed it. 😂
