### ISSUE TITLE
Update to 0.3.5

### ISSUE THREAD

**Issue by cbankester** [nitram509/macaroons.js#4]
Sorry to bother again (though, there's way more where this comes from; I'm going to be using macaroons.js in a production environment soon), but could we get updated to 0.3.5 and tagged with 0.3.5 so npm picks it up?

**Comment by cbankester** [comment]
@nitram509 Actually, if you find it permissible, contributor access to macaroons.js would greatly reduce my need to communicate/create issues for silly things like tags. Additionally, I would be able to extend the functionality of macaroons.js (perhaps on a separate branch and using tags like `1.3.5-beta`).

In order to dissuade any reservations you might have about allowing someone else access to your project, I assure you I will not commit or merge into master, or create tags that reduce or alter the functionality of macaroons.js from the perspective of anyone using it in their project(s).

Let me know if this is acceptable, or if you want any more information about my qualifications with regards to Node.js / npm; you can email me (my email address is on my [Github profile](https://github.com/cbankester)).

**Comment by nitram509** [comment]
@cbankester I'm actually very open to contributions and joined forces.
I've granted you push access to macaroons.js.
Macaroons.js should provide a demand-oriented library for using macaroons, but not being an individual solution for a concrete project/need.
Feel free to modify or extend the project according to its origin intend.
I'm open to any discussions, feedback and future development.

So welcome on board :-)

If you're interested to join macaroons.io Github organization to work on further macaroons related things, just drop me a note.
