### ISSUE TITLE
Useable in browser?

### ISSUE THREAD

**Issue by nyarly** [nitram509/macaroons.js#5]
Any guidance about using this within a browser session to e.g. attenuate a server-supplied macaroon?

**Comment by nitram509** [comment]
You can use it as a Cookie for example.
I even can safely contain certain session information.
Everyone can read it but not alter it ;-)

**Comment by nyarly** [comment]
Right, I understand how anyone can pass macaroons around - the question is, having received a macaroon, could JS running in the browser add further caveats and pass it along to a 3rd party? To do that, they'd need to parse the macaroon and do the crypto to add the new signature.

So, could this code be used in the browser to do that, or am I missing a node dependency?

**Comment by nitram509** [comment]
macaroons.js requires "typedarray-to-buffer" and "ecma-nacl".
AFAIK both aren#t available as ready to use in Browser.

Maybe http://browserify.org/ works for you?
Or you may use the GWT version, from https://github.com/macaroons-io/macaroons-io.github.io/tree/master.

Be aware, the moment you add cavaets in a browser to your macaroons, the moment an attacker may use the secret to also produce new tokens. This is just because macaroon keys are symmetric for minting and verifying macaroons.

**Comment by nyarly** [comment]
I'll need to look into it, I guess.

My thought is that the browser wouldn't ever be minting or verifying, only adding new caveats to an existing macaroon

**Comment by nitram509** [comment]
Yes indeed, also for adding new caveats you need to provide a secret.

e.g. 
````
var location = "http://www.example.org";
var secretKey = "this is our super secret key; only we should know it";
var identifier = "we used our secret key";
var macaroon = new MacaroonsBuilder(location, secretKey, identifier)
    .add_first_party_caveat("account = 3735928559")
    .getMacaroon();
````

**Comment by nyarly** [comment]
So, you're saying this won't work:

```
var macaroon = MacaroonsBuilder.modify(macaroon)
    .add_first_party_caveat("account = 3735928559")
    .getMacaroon();
```

**Comment by nitram509** [comment]
Indeed, that will work.
I had something different in mind regarding the immutability of macaroons.

**Comment by nitram509** [comment]
Sounds like everything is said :100: 
So I close this issue. Feel free to reopen in case you feel something important is missing.

**Comment by cbankester** [comment]
Just wanted to drop this resource here. @ecordell has a pretty good example of using macaroons.js in the browser for attenuation and such: https://github.com/ecordell/macaroon-session-example

**Comment by nitram509** [comment]
Thank you very much for pointing this out. :+1:
