### ISSUE TITLE
Can you nest 3rd party caveats?

### ISSUE THREAD

**Issue by GTDev87** [nitram509/macaroons.js#6]
I mean can you create a macaroon which has a 3rd party caveat which also has a 3rd party caveat using this library?  I've been trying to do this for a little while.

**Comment by nitram509** [comment]
Hi Greg,

currently direct nesting isn't supported.
I know the original paper explains the option of doing so,
but I'm not aware how much of support is currently available.

There's also the macaroons mailing list:
https://groups.google.com/forum/#!forum/macaroons
You may consider to describe your use case and send it 
to this list. I'm know there are experts listen, which could give you
better options to help solving the task you're working on.

Regards
Martin
